version: "3"

volumes:
  postgres_data:
    driver: local

services:
  gateway:
    image: eladen-gateway
    build:
      context: ./eladen-api-gateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - ./eladen-api-gateway:/code
    command: python manage.py runserver 0.0.0.0:${GATEWAY_PORT}
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DEBUG_FALSE=${DEBUG_FALSE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    container_name: eladen-gateway

  user-identity:
    build:
      context: ./eladen-useridentity-service
      dockerfile: Dockerfile
    volumes:
      - ./eladen-useridentity-service:/code
    command: python manage.py runserver 0.0.0.0:${UI_PORT}
    container_name: user-identity
  
  product-service:
    build:
      context: ./eladen-product-service
      dockerfile: Dockerfile
    volumes:
      - ./eladen-product-service:/code
    command: python manage.py runserver 0.0.0.0:${PS_PORT}
    container_name: product-service

  order-service:
    build:
      context: ./eladen-order-service
      dockerfile: Dockerfile
    volumes:
      - ./eladen-order-service:/code
    command: python manage.py runserver 0.0.0.0:${OS_PORT}
    container_name: order-service
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  checkout-service:
    build:
      context: ./eladen-checkout-service
      dockerfile: Dockerfile
    volumes:
      - ./eladen-checkout-service:/code
    container_name: checkout-service
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      ports:
        - "5672:5672"
        - "15672:15672"

networks:
  default:
    driver: bridge